// API Configuration and Utilities
const API_BASE_URL = process.env.REACT_APP_API_URL || 'http://localhost:3333/api';
const MASTER_API_KEY = process.env.REACT_APP_MASTER_API_KEY || 'changeme';

// DEBUG: Log the API URL being used
console.log('🔥 API_BASE_URL:', API_BASE_URL);
console.log('🔥 REACT_APP_API_URL env:', process.env.REACT_APP_API_URL);

/**
 * Sanitize header value to ensure it only contains ISO-8859-1 characters
 */
function sanitizeHeaderValue(value) {
  if (value == null) return '';
  const str = String(value);
  // Remove any characters that are not in ISO-8859-1 (0x00-0xFF)
  return str.split('').filter(char => {
    const code = char.charCodeAt(0);
    return code >= 0 && code <= 255;
  }).join('');
}

/**
 * Make API request with Master Admin authentication
 */
export async function apiRequest(endpoint, options = {}) {
  const url = `${API_BASE_URL}${endpoint}`;
  
  // Destructure headers from options to avoid conflicts
  const { headers: optionsHeaders, ...restOptions } = options;
  
  // Ensure all header values are strings and don't contain non-ISO-8859-1 characters
  const defaultHeaders = {
    'Content-Type': 'application/json',
    'x-api-key': sanitizeHeaderValue(MASTER_API_KEY)
  };
  
  // Merge headers safely, ensuring all values are sanitized
  const headers = {
    ...defaultHeaders,
    ...(optionsHeaders && Object.fromEntries(
      Object.entries(optionsHeaders).map(([key, value]) => [key, sanitizeHeaderValue(value)])
    ))
  };

  try {
    const response = await fetch(url, {
      ...restOptions,
      headers
    });

    if (!response.ok) {
      const error = await response.json().catch(() => ({ message: response.statusText }));
      throw new Error(error.message || `API Error: ${response.status}`);
    }

    return await response.json();
  } catch (error) {
    console.error('API Request Error:', error);
    throw error;
  }
}

/**
 * Get all tenants
 */
export async function getTenants() {
  return apiRequest('/tenants');
}

/**
 * Get a single tenant by ID
 */
export async function getTenant(tenantId) {
  if (!tenantId) {
    throw new Error('Tenant ID is required');
  }
  const tenants = await getTenants();
  return tenants.find(t => t.id === tenantId) || null;
}

/**
 * Create a new tenant
 */
export async function createTenant(name) {
  return apiRequest('/tenants', {
    method: 'POST',
    body: JSON.stringify({ name })
  });
}

/**
 * Get clubs for a tenant
 */
export async function getClubs(tenantId) {
  return apiRequest('/clubs', {
    headers: {
      'x-tenant-id': tenantId
    }
  });
}

/**
 * Create club with branding
 */
export async function createClubWithBranding(tenantId, clubData) {
  return apiRequest(`/tenants/${tenantId}/clubs`, {
    method: 'POST',
    body: JSON.stringify(clubData)
  });
}

/**
 * Create Super Admin (password auto-generated by backend)
 */
export async function createSuperAdmin(tenantId, superAdminData) {
  // superAdminData should only contain email and displayName
  // Password is auto-generated by backend
  return apiRequest(`/tenants/${tenantId}/super-admins`, {
    method: 'POST',
    body: JSON.stringify(superAdminData)
  });
}

/**
 * Setup tenant (club + super admin in one call)
 */
export async function setupTenant(tenantId, setupData) {
  return apiRequest(`/tenants/${tenantId}/setup`, {
    method: 'POST',
    body: JSON.stringify(setupData)
  });
}

/**
 * Get signed upload URL for club logo
 */
export async function getClubLogoUploadUrl(tenantId, clubId) {
  return apiRequest(`/tenants/${tenantId}/clubs/${clubId}/logo-upload-url`, {
    method: 'POST'
  });
}

/**
 * Upload file to signed URL
 */
export async function uploadFileToSignedUrl(signedUrl, file) {
  const response = await fetch(signedUrl, {
    method: 'PUT',
    body: file,
    headers: {
      'Content-Type': file.type
    }
  });

  if (!response.ok) {
    throw new Error(`Upload failed: ${response.statusText}`);
  }

  return response;
}

/**
 * Get public URL from Supabase storage path
 */
export function getPublicStorageUrl(path) {
  const supabaseUrl = process.env.REACT_APP_SUPABASE_URL || '';
  const bucket = process.env.REACT_APP_SUPABASE_BRANDING_BUCKET || 'branding';
  return `${supabaseUrl}/storage/v1/object/public/${bucket}/${path}`;
}

/**
 * Get all tenants a Super Admin has access to
 */
export async function getSuperAdminTenants(userId) {
  return apiRequest(`/users/${userId}/tenants`);
}

/**
 * Get all clubs a Super Admin can access
 */
export async function getSuperAdminClubs(userId) {
  return apiRequest(`/users/${userId}/clubs`);
}

/**
 * Get all clubs an Admin (or other club-scoped user) has access to
 */
export async function getAdminClubs(userId) {
  return apiRequest(`/users/${userId}/admin-clubs`);
}

/**
 * Login with email and password
 */
export async function login(email, password) {
  return apiRequest('/auth/login', {
    method: 'POST',
    body: JSON.stringify({ email, password })
  });
}

/**
 * Reset password (for first login)
 */
export async function resetPassword(email, currentPassword, newPassword) {
  return apiRequest('/auth/reset-password', {
    method: 'POST',
    body: JSON.stringify({ email, currentPassword, newPassword })
  });
}

/**
 * Make API request with Super Admin authentication
 * Requires userId and tenantId from localStorage
 */
export async function superAdminApiRequest(endpoint, options = {}) {
  const superAdmin = JSON.parse(localStorage.getItem('superAdmin') || '{}');
  const userId = superAdmin.id;
  const tenantId = superAdmin.tenantId; // We'll need to set this when selecting a club
  
  if (!userId) {
    throw new Error('Super Admin not authenticated');
  }

  const url = `${API_BASE_URL}${endpoint}`;
  
  // Destructure headers from options to avoid conflicts
  const { headers: optionsHeaders, ...restOptions } = options;
  
  // Ensure all header values are strings and don't contain non-ISO-8859-1 characters
  const defaultHeaders = {
    'Content-Type': 'application/json',
    'x-api-key': sanitizeHeaderValue(MASTER_API_KEY),
    'x-user-id': sanitizeHeaderValue(userId)
  };
  
  if (tenantId) {
    defaultHeaders['x-tenant-id'] = sanitizeHeaderValue(tenantId);
  }
  
  // Merge headers safely, ensuring all values are sanitized
  const headers = {
    ...defaultHeaders,
    ...(optionsHeaders && Object.fromEntries(
      Object.entries(optionsHeaders).map(([key, value]) => [key, sanitizeHeaderValue(value)])
    ))
  };

  try {
    const response = await fetch(url, {
      ...restOptions,
      headers
    });

    if (!response.ok) {
      const error = await response.json().catch(() => ({ message: response.statusText }));
      throw new Error(error.message || `API Error: ${response.status}`);
    }

    return await response.json();
  } catch (error) {
    console.error('Super Admin API Request Error:', error);
    throw error;
  }
}

/**
 * Make API request with Admin (or other club-scoped user) authentication
 * Requires userId and clubId from localStorage
 */
export async function adminApiRequest(endpoint, options = {}) {
  const admin = JSON.parse(localStorage.getItem('admin') || '{}');
  const userId = admin.id;
  const clubId = admin.clubId;
  const tenantId = admin.tenantId;
  
  if (!userId) {
    throw new Error('Admin not authenticated');
  }

  if (!clubId) {
    throw new Error('Club ID not set. Please select a club.');
  }

  const url = `${API_BASE_URL}${endpoint}`;
  
  // Destructure headers from options to avoid conflicts
  const { headers: optionsHeaders, ...restOptions } = options;
  
  // Ensure all header values are strings and don't contain non-ISO-8859-1 characters
  const defaultHeaders = {
    'Content-Type': 'application/json',
    'x-api-key': sanitizeHeaderValue(MASTER_API_KEY),
    'x-user-id': sanitizeHeaderValue(userId),
    'x-club-id': sanitizeHeaderValue(clubId)
  };
  
  if (tenantId) {
    defaultHeaders['x-tenant-id'] = sanitizeHeaderValue(tenantId);
  }
  
  // Merge headers safely, ensuring all values are sanitized
  const headers = {
    ...defaultHeaders,
    ...(optionsHeaders && Object.fromEntries(
      Object.entries(optionsHeaders).map(([key, value]) => [key, sanitizeHeaderValue(value)])
    ))
  };

  try {
    const response = await fetch(url, {
      ...restOptions,
      headers
    });

    if (!response.ok) {
      const error = await response.json().catch(() => ({ message: response.statusText }));
      throw new Error(error.message || `API Error: ${response.status}`);
    }

    return await response.json();
  } catch (error) {
    console.error('Admin API Request Error:', error);
    throw error;
  }
}

/**
 * Get club details
 * Works for both Super Admin (with tenantId) and Admin (with clubId in adminApiRequest)
 */
export async function getClub(clubId, tenantId) {
  // Check if we're using Admin authentication
  const admin = JSON.parse(localStorage.getItem('admin') || '{}');
  if (admin.id && admin.clubId) {
    // Use Admin API request
    return adminApiRequest(`/clubs/${clubId}`);
  } else {
    // Use Super Admin API request
    return superAdminApiRequest(`/clubs/${clubId}`, {
      headers: {
        'x-tenant-id': tenantId
      }
    });
  }
}

/**
 * Get club revenue, rake, and tips
 */
export async function getClubRevenue(clubId, tenantId) {
  return superAdminApiRequest(`/clubs/${clubId}/revenue`, {
    headers: {
      'x-tenant-id': tenantId
    }
  });
}

/**
 * Create a club-scoped user (Admin, Manager, HR, Staff, Affiliate, Cashier, GRE)
 */
export async function createClubUser(clubId, tenantId, userData) {
  return superAdminApiRequest(`/clubs/${clubId}/users`, {
    method: 'POST',
    headers: {
      'x-tenant-id': tenantId
    },
    body: JSON.stringify(userData)
  });
}

/**
 * List all users for a club
 */
export async function listClubUsers(clubId, tenantId) {
  return superAdminApiRequest(`/clubs/${clubId}/users`, {
    headers: {
      'x-tenant-id': tenantId
    }
  });
}

/**
 * Remove a role from a user in a club
 */
export async function removeClubUserRole(clubId, tenantId, userId, role) {
  return superAdminApiRequest(`/clubs/${clubId}/users/${userId}/roles/${role}`, {
    method: 'DELETE',
    headers: {
      'x-tenant-id': tenantId
    }
  });
}

/**
 * Create another Super Admin for the same tenant (Super Admin can do this)
 */
export async function createSuperAdminForTenant(tenantId, superAdminData) {
  return superAdminApiRequest(`/tenants/${tenantId}/super-admins`, {
    method: 'POST',
    headers: {
      'x-tenant-id': tenantId
    },
    body: JSON.stringify(superAdminData)
  });
}

// ========== Staff Management ==========
// Staff management works for both Super Admin and Admin
export async function getClubStaff(clubId, tenantId) {
  const admin = JSON.parse(localStorage.getItem('admin') || '{}');
  if (admin.id && admin.clubId) {
    // Use Admin API request
    return adminApiRequest(`/clubs/${clubId}/staff`);
  } else {
    // Use Super Admin API request
    return superAdminApiRequest(`/clubs/${clubId}/staff`, {
      headers: { 'x-tenant-id': tenantId }
    });
  }
}

export async function createStaff(clubId, tenantId, staffData) {
  const admin = JSON.parse(localStorage.getItem('admin') || '{}');
  if (admin.id && admin.clubId) {
    // Use Admin API request
    return adminApiRequest(`/clubs/${clubId}/staff`, {
      method: 'POST',
      body: JSON.stringify(staffData)
    });
  } else {
    // Use Super Admin API request
    return superAdminApiRequest(`/clubs/${clubId}/staff`, {
      method: 'POST',
      headers: { 'x-tenant-id': tenantId },
      body: JSON.stringify(staffData)
    });
  }
}

export async function updateStaff(clubId, tenantId, staffId, staffData) {
  const admin = JSON.parse(localStorage.getItem('admin') || '{}');
  if (admin.id && admin.clubId) {
    // Use Admin API request
    return adminApiRequest(`/clubs/${clubId}/staff/${staffId}`, {
      method: 'PUT',
      body: JSON.stringify(staffData)
    });
  } else {
    // Use Super Admin API request
    return superAdminApiRequest(`/clubs/${clubId}/staff/${staffId}`, {
      method: 'PUT',
      headers: { 'x-tenant-id': tenantId },
      body: JSON.stringify(staffData)
    });
  }
}

export async function deleteStaff(clubId, tenantId, staffId) {
  const admin = JSON.parse(localStorage.getItem('admin') || '{}');
  if (admin.id && admin.clubId) {
    // Use Admin API request
    return adminApiRequest(`/clubs/${clubId}/staff/${staffId}`, {
      method: 'DELETE'
    });
  } else {
    // Use Super Admin API request
    return superAdminApiRequest(`/clubs/${clubId}/staff/${staffId}`, {
      method: 'DELETE',
      headers: { 'x-tenant-id': tenantId }
    });
  }
}

// ========== Credit Requests ==========
export async function getCreditRequests(clubId, tenantId, status) {
  const url = status 
    ? `/clubs/${clubId}/credit-requests?status=${status}`
    : `/clubs/${clubId}/credit-requests`;
  return superAdminApiRequest(url, {
    headers: { 'x-tenant-id': tenantId }
  });
}

export async function createCreditRequest(clubId, tenantId, requestData) {
  return superAdminApiRequest(`/clubs/${clubId}/credit-requests`, {
    method: 'POST',
    headers: { 'x-tenant-id': tenantId },
    body: JSON.stringify(requestData)
  });
}

export async function approveCreditRequest(clubId, tenantId, requestId, limit) {
  return superAdminApiRequest(`/clubs/${clubId}/credit-requests/${requestId}/approve`, {
    method: 'POST',
    headers: { 'x-tenant-id': tenantId },
    body: JSON.stringify({ limit })
  });
}

export async function denyCreditRequest(clubId, tenantId, requestId) {
  return superAdminApiRequest(`/clubs/${clubId}/credit-requests/${requestId}/deny`, {
    method: 'POST',
    headers: { 'x-tenant-id': tenantId }
  });
}

export async function updateCreditVisibility(clubId, tenantId, requestId, visible) {
  return superAdminApiRequest(`/clubs/${clubId}/credit-requests/${requestId}/visibility`, {
    method: 'PUT',
    headers: { 'x-tenant-id': tenantId },
    body: JSON.stringify({ visible })
  });
}

export async function updateCreditLimit(clubId, tenantId, requestId, limit) {
  return superAdminApiRequest(`/clubs/${clubId}/credit-requests/${requestId}/limit`, {
    method: 'PUT',
    headers: { 'x-tenant-id': tenantId },
    body: JSON.stringify({ limit })
  });
}

// ========== Financial Transactions ==========
export async function getTransactions(clubId, tenantId, status) {
  const url = status 
    ? `/clubs/${clubId}/transactions?status=${status}`
    : `/clubs/${clubId}/transactions`;
  return superAdminApiRequest(url, {
    headers: { 'x-tenant-id': tenantId }
  });
}

export async function createTransaction(clubId, tenantId, transactionData) {
  return superAdminApiRequest(`/clubs/${clubId}/transactions`, {
    method: 'POST',
    headers: { 'x-tenant-id': tenantId },
    body: JSON.stringify(transactionData)
  });
}

export async function updateTransaction(clubId, tenantId, transactionId, transactionData) {
  return superAdminApiRequest(`/clubs/${clubId}/transactions/${transactionId}`, {
    method: 'PUT',
    headers: { 'x-tenant-id': tenantId },
    body: JSON.stringify(transactionData)
  });
}

export async function cancelTransaction(clubId, tenantId, transactionId) {
  return superAdminApiRequest(`/clubs/${clubId}/transactions/${transactionId}/cancel`, {
    method: 'POST',
    headers: { 'x-tenant-id': tenantId }
  });
}

// ========== VIP Products ==========
export async function getVipProducts(clubId, tenantId) {
  return superAdminApiRequest(`/clubs/${clubId}/vip-products`, {
    headers: { 'x-tenant-id': tenantId }
  });
}

export async function createVipProduct(clubId, tenantId, productData) {
  return superAdminApiRequest(`/clubs/${clubId}/vip-products`, {
    method: 'POST',
    headers: { 'x-tenant-id': tenantId },
    body: JSON.stringify(productData)
  });
}

export async function updateVipProduct(clubId, tenantId, productId, productData) {
  return superAdminApiRequest(`/clubs/${clubId}/vip-products/${productId}`, {
    method: 'PUT',
    headers: { 'x-tenant-id': tenantId },
    body: JSON.stringify(productData)
  });
}

export async function deleteVipProduct(clubId, tenantId, productId) {
  return superAdminApiRequest(`/clubs/${clubId}/vip-products/${productId}`, {
    method: 'DELETE',
    headers: { 'x-tenant-id': tenantId }
  });
}

// ========== Club Settings ==========
export async function getClubSettings(clubId, tenantId) {
  return superAdminApiRequest(`/clubs/${clubId}/settings`, {
    headers: { 'x-tenant-id': tenantId }
  });
}

export async function setClubSetting(clubId, tenantId, key, value) {
  return superAdminApiRequest(`/clubs/${clubId}/settings/${key}`, {
    method: 'PUT',
    headers: { 'x-tenant-id': tenantId },
    body: JSON.stringify({ value })
  });
}

// ========== Audit Logs ==========
export async function getAuditLogs(clubId, tenantId, options = {}) {
  const { limit, action, entityType, startDate, endDate } = options;
  const params = new URLSearchParams();
  if (limit) params.append('limit', limit);
  if (action) params.append('action', action);
  if (entityType) params.append('entityType', entityType);
  if (startDate) params.append('startDate', startDate);
  if (endDate) params.append('endDate', endDate);
  
  const url = `/clubs/${clubId}/audit-logs${params.toString() ? '?' + params.toString() : ''}`;
  return superAdminApiRequest(url, {
    headers: { 'x-tenant-id': tenantId }
  });
}

export async function exportAuditLogs(clubId, tenantId, options = {}) {
  const { startDate, endDate, format = 'json' } = options;
  const params = new URLSearchParams();
  if (startDate) params.append('startDate', startDate);
  if (endDate) params.append('endDate', endDate);
  if (format) params.append('format', format);
  
  const url = `/clubs/${clubId}/audit-logs/export${params.toString() ? '?' + params.toString() : ''}`;
  return superAdminApiRequest(url, {
    headers: { 'x-tenant-id': tenantId }
  });
}

// ========== Waitlist & Seating ==========
export async function createWaitlistEntry(clubId, tenantId, entryData) {
  return superAdminApiRequest(`/clubs/${clubId}/waitlist`, {
    method: 'POST',
    headers: { 'x-tenant-id': tenantId },
    body: JSON.stringify(entryData)
  });
}

export async function getWaitlist(clubId, tenantId, status) {
  const url = status 
    ? `/clubs/${clubId}/waitlist?status=${status}`
    : `/clubs/${clubId}/waitlist`;
  return superAdminApiRequest(url, {
    headers: { 'x-tenant-id': tenantId }
  });
}

export async function getWaitlistEntry(clubId, tenantId, entryId) {
  return superAdminApiRequest(`/clubs/${clubId}/waitlist/${entryId}`, {
    headers: { 'x-tenant-id': tenantId }
  });
}

export async function updateWaitlistEntry(clubId, tenantId, entryId, entryData) {
  return superAdminApiRequest(`/clubs/${clubId}/waitlist/${entryId}`, {
    method: 'PUT',
    headers: { 'x-tenant-id': tenantId },
    body: JSON.stringify(entryData)
  });
}

export async function cancelWaitlistEntry(clubId, tenantId, entryId) {
  return superAdminApiRequest(`/clubs/${clubId}/waitlist/${entryId}/cancel`, {
    method: 'POST',
    headers: { 'x-tenant-id': tenantId }
  });
}

export async function deleteWaitlistEntry(clubId, tenantId, entryId) {
  return superAdminApiRequest(`/clubs/${clubId}/waitlist/${entryId}`, {
    method: 'DELETE',
    headers: { 'x-tenant-id': tenantId }
  });
}

export async function assignSeat(clubId, tenantId, entryId, tableId, userId) {
  return superAdminApiRequest(`/clubs/${clubId}/waitlist/${entryId}/assign-seat`, {
    method: 'POST',
    headers: { 
      'x-tenant-id': tenantId,
      'x-user-id': userId
    },
    body: JSON.stringify({ tableId, seatedBy: userId })
  });
}

export async function unseatPlayer(clubId, tenantId, entryId) {
  return superAdminApiRequest(`/clubs/${clubId}/waitlist/${entryId}/unseat`, {
    method: 'POST',
    headers: { 'x-tenant-id': tenantId }
  });
}

// ========== Tables ==========
export async function createTable(clubId, tenantId, tableData) {
  return superAdminApiRequest(`/clubs/${clubId}/tables`, {
    method: 'POST',
    headers: { 'x-tenant-id': tenantId },
    body: JSON.stringify(tableData)
  });
}

export async function getTables(clubId, tenantId, filters = {}) {
  const { status, tableType } = filters;
  const params = new URLSearchParams();
  if (status) params.append('status', status);
  if (tableType) params.append('tableType', tableType);
  
  const url = `/clubs/${clubId}/tables${params.toString() ? '?' + params.toString() : ''}`;
  return superAdminApiRequest(url, {
    headers: { 'x-tenant-id': tenantId }
  });
}

export async function getTable(clubId, tenantId, tableId) {
  return superAdminApiRequest(`/clubs/${clubId}/tables/${tableId}`, {
    headers: { 'x-tenant-id': tenantId }
  });
}

export async function updateTable(clubId, tenantId, tableId, tableData) {
  return superAdminApiRequest(`/clubs/${clubId}/tables/${tableId}`, {
    method: 'PUT',
    headers: { 'x-tenant-id': tenantId },
    body: JSON.stringify(tableData)
  });
}

export async function deleteTable(clubId, tenantId, tableId) {
  return superAdminApiRequest(`/clubs/${clubId}/tables/${tableId}`, {
    method: 'DELETE',
    headers: { 'x-tenant-id': tenantId }
  });
}

// ========== Analytics & Reports ==========
export async function getRevenueAnalytics(clubId, tenantId, options = {}) {
  const { startDate, endDate } = options;
  const params = new URLSearchParams();
  if (startDate) params.append('startDate', startDate);
  if (endDate) params.append('endDate', endDate);
  
  const url = `/clubs/${clubId}/analytics/revenue${params.toString() ? '?' + params.toString() : ''}`;
  return superAdminApiRequest(url, {
    headers: { 'x-tenant-id': tenantId }
  });
}

export async function getPlayerAnalytics(clubId, tenantId, options = {}) {
  const { startDate, endDate } = options;
  const params = new URLSearchParams();
  if (startDate) params.append('startDate', startDate);
  if (endDate) params.append('endDate', endDate);
  
  const url = `/clubs/${clubId}/analytics/players${params.toString() ? '?' + params.toString() : ''}`;
  return superAdminApiRequest(url, {
    headers: { 'x-tenant-id': tenantId }
  });
}

export async function getStaffAnalytics(clubId, tenantId) {
  return superAdminApiRequest(`/clubs/${clubId}/analytics/staff`, {
    headers: { 'x-tenant-id': tenantId }
  });
}

export async function getTableAnalytics(clubId, tenantId) {
  return superAdminApiRequest(`/clubs/${clubId}/analytics/tables`, {
    headers: { 'x-tenant-id': tenantId }
  });
}

export async function getWaitlistAnalytics(clubId, tenantId, options = {}) {
  const { startDate, endDate } = options;
  const params = new URLSearchParams();
  if (startDate) params.append('startDate', startDate);
  if (endDate) params.append('endDate', endDate);
  
  const url = `/clubs/${clubId}/analytics/waitlist${params.toString() ? '?' + params.toString() : ''}`;
  return superAdminApiRequest(url, {
    headers: { 'x-tenant-id': tenantId }
  });
}

export async function getDashboardStats(clubId, tenantId) {
  return superAdminApiRequest(`/clubs/${clubId}/analytics/dashboard`, {
    headers: { 'x-tenant-id': tenantId }
  });
}

// ========== Global Settings (Enhanced) ==========
export async function getClubSetting(clubId, tenantId, key) {
  return superAdminApiRequest(`/clubs/${clubId}/settings/${key}`, {
    headers: { 'x-tenant-id': tenantId }
  });
}

export async function deleteClubSetting(clubId, tenantId, key) {
  return superAdminApiRequest(`/clubs/${clubId}/settings/${key}`, {
    method: 'DELETE',
    headers: { 'x-tenant-id': tenantId }
  });
}

// ========== Dashboard Stats ==========
export async function getClubStats(clubId, tenantId) {
  return superAdminApiRequest(`/clubs/${clubId}/stats`, {
    headers: { 'x-tenant-id': tenantId }
  });
}

// ========== Affiliate Management ==========
export async function createAffiliate(clubId, tenantId, affiliateData) {
  return superAdminApiRequest(`/clubs/${clubId}/affiliates`, {
    method: 'POST',
    headers: { 'x-tenant-id': tenantId },
    body: JSON.stringify(affiliateData)
  });
}

export async function getAffiliates(clubId, tenantId) {
  return superAdminApiRequest(`/clubs/${clubId}/affiliates`, {
    headers: { 'x-tenant-id': tenantId }
  });
}

export async function getAffiliateStats(clubId, tenantId, affiliateId) {
  return superAdminApiRequest(`/clubs/${clubId}/affiliates/${affiliateId}/stats`, {
    headers: { 'x-tenant-id': tenantId }
  });
}

export async function getAffiliatePlayers(clubId, tenantId, affiliateId) {
  return superAdminApiRequest(`/clubs/${clubId}/affiliates/${affiliateId}/players`, {
    headers: { 'x-tenant-id': tenantId }
  });
}

// ========== Player Management ==========
export async function createPlayer(clubId, tenantId, playerData) {
  return apiRequest(`/clubs/${clubId}/players`, {
    method: 'POST',
    headers: { 'x-tenant-id': tenantId },
    body: JSON.stringify(playerData)
  });
}

// For affiliate users
export async function affiliateApiRequest(endpoint, options = {}) {
  const adminStr = localStorage.getItem('admin');
  if (!adminStr) {
    throw new Error('Not authenticated');
  }
  const admin = JSON.parse(adminStr);
  
  const url = `${API_BASE_URL}${endpoint}`;
  const { headers: optionsHeaders, ...restOptions } = options;
  
  const defaultHeaders = {
    'Content-Type': 'application/json',
    'x-user-id': sanitizeHeaderValue(admin.userId || ''),
    'x-tenant-id': sanitizeHeaderValue(admin.tenantId || ''),
    'x-club-id': sanitizeHeaderValue(admin.clubId || '')
  };
  
  const headers = {
    ...defaultHeaders,
    ...(optionsHeaders && Object.fromEntries(
      Object.entries(optionsHeaders).map(([key, value]) => [key, sanitizeHeaderValue(value)])
    ))
  };

  try {
    const response = await fetch(url, {
      ...restOptions,
      headers
    });

    if (!response.ok) {
      const error = await response.json().catch(() => ({ message: response.statusText }));
      throw new Error(error.message || `API Error: ${response.status}`);
    }

    return await response.json();
  } catch (error) {
    console.error('API Request Error:', error);
    throw error;
  }
}

export async function getMyAffiliateStats(clubId) {
  const adminStr = localStorage.getItem('admin');
  if (!adminStr) {
    throw new Error('Not authenticated');
  }
  const admin = JSON.parse(adminStr);
  
  // First get affiliates to find our affiliate ID
  const affiliates = await affiliateApiRequest(`/clubs/${clubId}/affiliates`);
  const myAffiliate = affiliates.find(a => a.email === admin.email);
  
  if (!myAffiliate) {
    throw new Error('Affiliate not found');
  }
  
  return affiliateApiRequest(`/clubs/${clubId}/affiliates/${myAffiliate.id}/stats`);
}

export async function getMyAffiliatePlayers(clubId) {
  const adminStr = localStorage.getItem('admin');
  if (!adminStr) {
    throw new Error('Not authenticated');
  }
  const admin = JSON.parse(adminStr);
  
  // First get affiliates to find our affiliate ID
  const affiliates = await affiliateApiRequest(`/clubs/${clubId}/affiliates`);
  const myAffiliate = affiliates.find(a => a.email === admin.email);
  
  if (!myAffiliate) {
    throw new Error('Affiliate not found');
  }
  
  return affiliateApiRequest(`/clubs/${clubId}/affiliates/${myAffiliate.id}/players`);
}

// ========== Player Portal APIs ==========

/**
 * Make API request with Player authentication
 * Requires playerId and clubId from localStorage
 */
export async function playerApiRequest(endpoint, options = {}) {
  const player = JSON.parse(localStorage.getItem('player') || '{}');
  const playerId = player.id;
  const clubId = player.clubId;
  
  if (!playerId) {
    throw new Error('Player not authenticated');
  }

  if (!clubId) {
    throw new Error('Club ID not set');
  }

  const url = `${API_BASE_URL}${endpoint}`;
  
  const { headers: optionsHeaders, ...restOptions } = options;
  
  const defaultHeaders = {
    'Content-Type': 'application/json',
    'x-player-id': sanitizeHeaderValue(playerId),
    'x-club-id': sanitizeHeaderValue(clubId)
  };
  
  const headers = {
    ...defaultHeaders,
    ...(optionsHeaders && Object.fromEntries(
      Object.entries(optionsHeaders).map(([key, value]) => [key, sanitizeHeaderValue(value)])
    ))
  };

  try {
    const response = await fetch(url, {
      ...restOptions,
      headers
    });

    if (!response.ok) {
      const error = await response.json().catch(() => ({ message: response.statusText }));
      throw new Error(error.message || `API Error: ${response.status}`);
    }

    return await response.json();
  } catch (error) {
    console.error('Player API Request Error:', error);
    throw error;
  }
}

// ========== Club Code Verification ==========
export async function verifyClubCode(clubCode) {
  return apiRequest('/clubs/verify-code', {
    method: 'POST',
    body: JSON.stringify({ code: clubCode })
  });
}

// ========== Player Authentication ==========
export async function playerLogin(clubCode, email, password) {
  return apiRequest('/auth/player/login', {
    method: 'POST',
    body: JSON.stringify({ clubCode, email, password })
  });
}

export async function playerSignup(clubCode, signupData) {
  return apiRequest('/auth/player/signup', {
    method: 'POST',
    body: JSON.stringify({
      clubCode,
      firstName: signupData.firstName,
      lastName: signupData.lastName,
      email: signupData.email,
      password: signupData.password,
      phoneNumber: signupData.phoneNumber,
      nickname: signupData.nickname,
      referralCode: signupData.referralCode
    })
  });
}

// ========== Player Profile ==========
export async function getPlayerProfile() {
  return playerApiRequest('/auth/player/me');
}

export async function updatePlayerProfile(profileData) {
  return playerApiRequest('/auth/player/profile', {
    method: 'PUT',
    body: JSON.stringify(profileData)
  });
}

export async function changePlayerPassword(currentPassword, newPassword) {
  return playerApiRequest('/auth/player/change-password', {
    method: 'POST',
    body: JSON.stringify({ currentPassword, newPassword })
  });
}

// ========== Player Balance & Transactions ==========
export async function getPlayerBalance() {
  return playerApiRequest('/auth/player/balance');
}

export async function getPlayerTransactions(limit = 50, offset = 0) {
  return playerApiRequest(`/auth/player/transactions?limit=${limit}&offset=${offset}`);
}

// ========== Waitlist Management ==========
export async function joinWaitlist(tableType, partySize = 1) {
  return playerApiRequest('/auth/player/waitlist', {
    method: 'POST',
    body: JSON.stringify({ tableType, partySize })
  });
}

export async function getWaitlistStatus() {
  return playerApiRequest('/auth/player/waitlist');
}

export async function cancelWaitlist(entryId) {
  return playerApiRequest(`/auth/player/waitlist/${entryId}`, {
    method: 'DELETE'
  });
}

// ========== Tables ==========
export async function getAvailableTables() {
  return playerApiRequest('/auth/player/tables');
}

export async function getTableDetails(tableId) {
  return playerApiRequest(`/auth/player/tables/${tableId}`);
}

// ========== Credit & Stats ==========
export async function requestCredit(amount, notes) {
  return playerApiRequest('/auth/player/credit-request', {
    method: 'POST',
    body: JSON.stringify({ amount, notes })
  });
}

export async function getPlayerStats() {
  return playerApiRequest('/auth/player/stats');
}

